apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-docgen.fullname" . }}-secrets
  labels:
    {{- include "ai-docgen.labels" . | nindent 4 }}
type: Opaque
data:
  llm-api-key: {{ .Values.config.llmApiKey | b64enc | quote }}
