apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-docgen.fullname" . }}
  labels:
    {{- include "ai-docgen.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portWeb }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-docgen.selectorLabels" . | nindent 4 }}
